language: cpp
compiler:
  - gcc
sudo: false  
env:
  - RDM_QT_VERSION=55
  - RDM_QT_VERSION=542
addons:
  apt:
    sources:
      - beineri/opt-qt${RDM_QT_VERSION}
      - ubuntu-toolchain-r/tes
    packages:
      - qt${RDM_QT_VERSION:0:2}base
      - qt${RDM_QT_VERSION:0:2}imageformats
      - qt${RDM_QT_VERSION:0:2}tools
      - libssl1.0.0
      - libssh2-1-dev
      - gdb
      - gcc-4.9 
      - g++-4.9
before_install:
- gcc --version
- qmake -v
- export PATH=/usr/bin/gcov-4.9:$PATH
- source /opt/qt${RDM_QT_VERSION:0:2}/bin/qt${RDM_QT_VERSION:0:2}-env.sh
install:
  - pip install cpp-coveralls
script: 
  - cd ./tests
  - qmake DEFINES+=INTEGRATION_TESTS QMAKE_CXX=g++-4.9 QMAKE_CC=gcc-4.9
  - make -s -j 3
  - ./../bin/tests/tests -platform minimal -txt
  - ./../bin/tests/qml_tests -platform minimal -txt
  - cd ./../src
  - qmake QMAKE_CXX=g++-4.9 QMAKE_CC=gcc-4.9
  - make -s -j 3
after_success:
  - cd ./../tests
  - coveralls -b `pwd`/unit_tests/ -r `readlink -m ./../` -e 3rdparty/ -e tests/ -E .+/moc_.* -E .+/qrc_.* -E .+/qxt.* -E .+/ui_.*  > coveralls.log
services:
  - redis-server
notifications:
  recipients:
    - u.glide@gmail.com
  email:
    on_success: change
    on_failure: change
